---
- name: build and install nagios-plugin
  shell: |
    chdir=/usr/local/src
    if [ ! -f nagios-plugins-{{ nagios_plugin_version }}.tar.gz ]; then
      wget http://nagios-plugins.org/download/nagios-plugins-{{ nagios_plugin_version }}.tar.gz
      tar xfz nagios-plugins-{{ nagios_plugin_version }}.tar.gz
    fi

    /usr/local/nagios/bin/nagios --version

    if [ 0 != `echo $?` ];then
      cd nagios-plugins-{{ nagios_plugin_version }}
      ./configure --with-nagios-user=nagios --with-nagios-group=nagios
      make
      make install
    else
      echo "not install"
    fi
