---
- name: Install ganglia-gmond
  yum: name={{item}} state=installed
  with_items:
    - ganglia-gmond
  tags: gagnglia-gmond

- name: gmond config file
  template: >
     src=gmond.conf.j2
     dest=/etc/ganglia/gmond.conf
     owner=root
     group=root
     mode=0644
