---

- name: download ganglia-web source
  get_url: >
    url=http://jaist.dl.sourceforge.net/project/ganglia/ganglia-web/{{ ganglia_web_version }}/ganglia-web-{{ ganglia_web_version }}.tar.gz
    dest=/usr/local/src/ganglia-web-{{ ganglia_web_version }}.tar.gz

- name: build and install ganglia-web
  shell: |
    chdir=/usr/local/src
    creates=/usr/share/ganglia 
    tar xf ganglia-web-{{ ganglia_web_version }}.tar.gz &&
    cd ganglia-web-{{ ganglia_web_version }} &&
    make install APACHE_USER=apache GDESTDIR=/usr/share/ganglia

#- name: ganglia config file for nginx
#  template: >
#    src=ganglia.nginx.ssl.conf.j2
#    dest=/etc/nginx/conf.d/ssl.location.d/ganglia.conf
#    owner=root
#    group=root
#    mode=0644
#  notify: reload nginx
