---
- name: graphite local settings
  template: >
     src=local_settings.py.j2
     dest=/etc/graphite-web/local_settings.py
     owner=root
     group=root
     mode=0755

- name: graphite DB and User Create
  template: >
     src=init_graphitedb.sh.j2
     dest=/tmp/init_graphitedb.sh
     owner=root
     group=root
     mode=0755

#- name: gmond run file
#  shell: sh /tmp/init_graphitedb.sh
