---
- name: graphite local settings
  template: >
     src=local_settings.py.j2
     dest=/etc/graphite-web/local_settings.py
     owner=root
     group=root
     mode=0755

- name: graphite DB and User Create
  template: >
     src=init_graphitedb.sh.j2
     dest=/tmp/init_graphitedb.sh
     owner=root
     group=root
     mode=0755

- name: graphite-web apache conf
  template: >
     src=graphite-web.conf.j2
     dest=/etc/httpd/conf.d/graphite-web.conf
     owner=root
     group=root
     mode=0755
#- name: run initdb
#  shell: sh /tmp/init_graphitedb.sh

- name: Graphite syncdb
  shell: |
    /usr/lib/python2.6/site-packages/graphite/manage.py syncdb --noinput
