---
- name: be sure mysql repository is installed
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
  tags: mysql-community-repo

- name: Install mysql
  yum: name={{item}} state=installed enablerepo=mysql56-community
  with_items:
    - mysql-community-server
    - mysql-community-devel
  tags: MySQL

- name: mysql dir chmod
  shell: |
    chown -R mysql:mysql /var/lib/mysql

- name: mysqld is running and enabled
  service: name=mysqld state=running enabled=yes

#- name: root password setting
#  shell: |
#    /usr/bin/mysqladmin -u root -h localhost.localdomain password '{{ mysql_password }}'
